### DISCUSSION TITLE
Provision of citation metadata for documentation / reference purposes?

### DISCUSSION THREAD

**Discussion by kevinmatthes** [sourcefrog/cargo-mutants#210] [Ideas]
First of all, merry Christmas! :christmas_tree: :gift: :tada:

I would like to suggest the configuration of a CITATION.cff which would be used by GitHub to render a "Cite this repository" blob on the project's landing page.  This is useful for users who intended to mention `cargo-mutants` in their academic publications as well as their own CITATION.cff files as this file format offers an optional list of references.  Citations of this project can be considered free advertisement since readers of the papers would learn about `cargo-mutants`.  In addition, the `authors` section of a CITATION.cff can be also employed as a curated list of contributors whose provision is not uncommon within the open source community.

As I experiment with `cargo-mutants` as part of the CI of one my projects, at the moment, which I also gave academic presentations for, (at least) I would be interested in being able to cite this project appropriately.  I already assisted several projects with the setup of a CITATION.cff, such as Clap and astropy, and I also implemented a set of tools for convenient creation and maintenance experiences of CITATION.cff files, so I am familiar with the necessary changes.  At the moment, it is possible to create an entirely self-maintaining CITATION.cff which is updated automatically by GitHub Actions such that no additional overhead would be introduced.

Thus, I would like to ask you if you might be interested in a CITATION.cff, @sourcefrog.

**Comment by sourcefrog** [comment]
Merry Christmas to you too! Yes, that sounds good. 

Please do send a PR.

Also, I'd be interested to see the papers that cite it.

**Reply by kevinmatthes** [reply]
The entire CFF setup package consists of the following changes:

- the CITATION.cff itself;
- the official CFF validation Action to ensure the validity (usually succeeds within 10 seconds; maintenance-free); and
- some GHA workflows to maintain the CITATION.cff automatically.

For the first point, the basic setup, my documentation assistant Aeruginous yields the following:

```yml
abstract: Find inadequately-tested code that can be removed without any tests failing.
authors:
  - name: Martin Pool
cff-version: 1.2.0
keywords:
  - Rust
  - cargo
  - coverage
  - development-tools::testing
  - mutants
  - mutation-testing
  - testing
license: MIT
message: Please cite this project using these information.
repository-code: https://github.com/sourcefrog/cargo-mutants
title: cargo-mutants
url: https://mutants.rs/
version: 23.12.2
```

The call to Aeruginous, just for completeness:

```
curl https://raw.githubusercontent.com/sourcefrog/cargo-mutants/main/Cargo.toml | aeruginous mkcff -m rs --suppress-release-date
```

This basic setup is generated from your Cargo.toml and is a valid starting point.  If this base configuration does not need any further customisation, the maintenance is rather straightforward:  on release, the CITATION.cff is re-created from the updated Cargo.toml and committed to the repository.  If you wish for further adjustments, we would just need to replace the outdated `version` and update the release date on release; both steps are simple `sed` commands which can be done within a workflow.

Please tell which adjustments to the data would be required such that I can prepare a PR.
